<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.6.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmsNotification.APPLICATION\SmsNotification.APPLICATION.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Redis\Scripts\token_bucket.lua" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
